apiVersion: apps/v1
kind: Deployment
metadata:
  name: permify-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: permify
  template:
    metadata:
      labels:
        app: permify
    spec:
      containers:
        - image: permify/permify:tagname
          name: permify
          args:
            - "serve"
            - "--database-engine=postgres"
            - "--database-uri=<database-dsn>"
            - "--database-max-open-connections=20"
            - "--distributed-enabled=true"
            - "--distributed-node=serf:7946"
            - "--distributed-node-name=main-serf"
            - "--distributed-protocol=serf"
          resources:
             requests:
               memory: "128Mi"
               cpu: "200m"
             limits:
              memory: "128Mi"
              cpu: "400m"
          ports:
          - containerPort: 3476
            name: permify-port
          - containerPort: 7946
            name: permify-dist
          - containerPort: 3478
            name: permify-rpc
          - containerPort: 6060
            name: permify-pprof
