apiVersion: v1
kind: Service
metadata:
  name: permify
  namespace: loadtest
spec:
  ports:
      - name: permify-port
        port: 3476
        targetPort: 3476
      - name: permify-dist
        port: 7946
        targetPort: 7946
      - name: permify-rpc
        port: 3478
        targetPort: 3478
  selector:
        app: permify
  type: LoadBalancer
