apiVersion: v1
kind: Service
metadata:
  name: permify-dist
spec:
  ports:
      - name: permify-dist
        port: 7946
        targetPort: 7946
  selector:
        app: permify
  type: LoadBalancer
