apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: permify-statefulset
spec:
  serviceName: "permify"
  replicas: 3
  selector:
    matchLabels:
      app: permify
  template:
    metadata:
      labels:
        app: permify
    spec:
      containers:
        - image: muratmirgun/permify-local:56
          name: permify
          args:
            - "serve"
            - "--database-engine=postgres"
            - "--database-uri=<database-dsn>"
            - "--database-max-open-connections=20"
            - "--distributed-enabled=true"
            - "--distributed-nodes=permify-statefulset-0.permify.default.svc.cluster.local:7946"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
          - containerPort: 3476
            name: permify-port
          - containerPort: 7946
            name: permify-dist
